- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: allcentos  
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root
  # gather_facts: no  

  tasks:

    # - name: Open http firewall port
    #   firewalld:
    #       service: http 
    #       zone: public
    #       immediate: yes # this is the firewall-cmd --reload
    #       permanent: true
    #       state: enabled

    - name: Install HTTPD on CentOS
      dnf:
        name: '{{ pkg }}'
        state: present
        update_cache: True
      with_items:
        - httpd
        - curl
 

    - name: httpd template for index.html
      template:
        src: file/index.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      notify: restart httpd



  handlers:
    - name: restart-apache
      service:
        name: httpd
        state: restarted
      listen: "restart-httpd"
      notify: check-url
    - name: Check URL
      uri:
        url: 'http://{{ http_host }}'
        method: GET 
      listen: check-url