- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: allcentos  
  # become_user: root
  become: true
  become_method: sudo
  # gather_facts: no  
  tasks:
    - name: Install HTTPD on CentOS
      dnf:
        name: 
          - httpd
          - curl          
        state: present
        update_cache: True
 
    - name: httpd template for index.html
      template:
        src: files/index.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      notify: restart-httpd

  handlers:
    - name: restart-apache
      service:
        name: httpd
        state: restarted
      listen: restart-httpd      
    - name: Check URL
      uri:
        url: 'http://{{ http_host }}'
        method: GET 
      listen: restart-httpd