- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: all
  become: yes
  # gather_facts: no

  tasks:
    - name: Install latest version of Apache httpd on Ubuntu
      apt: name=apache2 update_cache=yes state=latest
    
    - name: Install latest version of curl
      apt: name=curl update_cache=yes state=latest

    - name: Install httpd on CentOS
      dnf:
        name: httpd
        state: latest
      when:  
 
    - name: Create document root for domain configured in host variable
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
 
    - name: Copy your index file
      template:
        src: "files/index-template.html"
        dest: "/var/www/{{ http_host }}/index.html"
 
    - name: Set up virtuahHost
      template:
        src: "files/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
 
    - name: Enable site
      command: a2ensite {{ http_conf }}
      notify: restart-apache

    # - name: Check URL
    #   uri:
    #     url: 'http://{{ http_host }}'
    #     method: GET
      # register: result      
 
    # - name: "UFW firewall allow HTTP on port {{ http_port }}"
    #   ufw:
    #     rule: allow
    #     port: "{{ http_port }}"
    #     proto: tcp
 
  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted